version: '3'

networks:
  docker-network:
    driver: bridge

services:

  rocky:
    image: rocky
    container_name: rocky
    restart: always
    networks:
      - docker-network
    ports: 
      - 80:8080

