### STAGE 1: Build ###
FROM node:12.7-alpine AS build
WORKDIR /usr/src/app
COPY rocky-locust-frontend/package.json rocky-locust-frontend/package-lock.json ./
RUN npm install
COPY rocky-locust-frontend/ .
RUN npm run build

### STAGE 2: Run ###
FROM nginx:1.17.1-alpine
COPY rocky-locust-frontend/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /usr/src/app/dist /usr/share/nginx/html

